before_script:
   - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ quantal main universe"
   - sudo apt-get -q update
   - sudo apt-get install build-essential git autoconf cmake libprotobuf-dev python-protobuf protobuf-compiler protobuf-c-compiler libyaml-cpp-dev libzmq3-dev
language: cpp
script:
 - mkdir build
 - cd build
 - cmake ..
 - make
 - make install

# watch master and next branches only
branches:
 only:
   - travis
